substitutions:
  friendly_name: 'NESP'
  hostname: 'neo-nesp'
  device_name: 'neo_nesp'
  device_description: 'WT32S3-21S ZX2D10GE01R-V4848 rotary switch screen'
  ip: 10.0.80.75

  # Home Assistant entities you want to control with nESP
  climate_entity: climate.climate_control
  zone_1_entity: cover.zone_1_downstairs
  zone_2_entity: cover.zone_2_upstairs

  # Home Assistant weather/info entities
  weather_entity: weather.bom_melbourne
  weather_feels_like_entity: sensor.bom_melbourne_temp_feels_like
  weather_high_entity: sensor.bom_melbourne_temp_max_0
  weather_high_tmr_entity: sensor.bom_melbourne_temp_max_1
  weather_low_entity: sensor.bom_melbourne_temp_min_0
  weather_rain_chance_entity: sensor.bom_melbourne_rain_chance_0
  zone_1_temperature_entity: sensor.xiaomi_temp_1_temperature
  zone_1_humidity_entity: sensor.xiaomi_temp_1_humidity
  zone_2_temperature_entity: sensor.xiaomi_temp_2_temperature
  zone_2_humidity_entity: sensor.xiaomi_temp_2_humidity
  perimeter_entity: sensor.perimeter_trigger
  alarm_entity: alarm_control_panel.alarmo

external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: dev
    components: [ lvgl ]

esphome:
  name: ${hostname}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
    board_build.arduino.memory_type: qio_opi
  on_boot:
    - light.turn_on:
        id: backlight
        brightness: 0.7
    - script.execute: set_weather_bg

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.8.1
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

debug:
  update_interval: 60s

<<: !include _common.yaml

<<: !include _neo-nesp.yaml
<<: !include _neo-nesp_UI.yaml
