packages:
  api: !include nesp-common.yaml

esphome:
  name: ${device_name}
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: ${device_description}
  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: ${project_base}.${project_name}
    version: $project_version
  # special board needs special options
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.variant: esp32s3
# TAKEN FROM WLED MM - https://github.com/MoonModules/WLED
    build_flags: [
      "-DESP32",
      "-DARDUINO_ARCH_ESP32",
      "-DARDUINO_ARCH_ESP32S3",
      "-DCONFIG_IDF_TARGET_ESP32S3=1",
      "-D CONFIG_ASYNC_TCP_USE_WDT=0",
      "-DARDUINO_USB_MSC_ON_BOOT=0",
      "-DARDUINO_DFU_ON_BOOT=0",
      "-DCO"
##########################################################
#  ;; please make sure that the following flags are properly set (to 0 or 1) by your board.json
#  ;; ARDUINO_USB_MODE, ARDUINO_USB_CDC_ON_BOOT
##########################################################
      ]
  on_boot:
    priority: -100.0 #  At this priority, pretty much everything should already be initialized.
    then:
      - script.execute: show_page_boot

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: '5.3.0'
    platform_version: '6.8.0'
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y
      CONFIG_COMPILER_OPTIMIZATION: CONFIG_COMPILER_OPTIMIZATION_PERF
      CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION: BOOTLOADER_COMPILER_OPTIMIZATION_PERF
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_IDF_TARGET_ESP32S3: y
    advanced:
      ignore_efuse_mac_crc: true

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://velijv/nesp/nesp-s3.yaml@main