name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build_s2:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: nesp-s2.yaml
      name: nESP-S2

  build_s3:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: nesp-s3.yaml
      name: nESP-S3